# CloudFormation template for the Docker playground instance.  Parameters are supplied by Terraform.
# Author: Andrew Jarombek
# Date: 3/9/2019

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Playground EC2 instance for testing Docker'

Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC to deploy the Docker Playground in"
  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Subnet to deploy the Docker Playground in"
  MyCidr:
    Type: "String"
    Description: "CIDR for my local environment"
  PublicCidr:
    Type: "String"
    Description: "CIDR for all IP addresses"

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Terraform AWS Data"
      Parameters:
      - VpcId
      - SubnetId
      - MyCidr
      - PublicCidr
    ParameterLabels:
      VpcId:
        default: "VPC to deploy the EC2 instance in"
      SubnetId:
        default: "Subnet to deploy the EC2 instance in"
      MyCidr:
        default: "CIDR for my local environment"
      PublicCidr:
        default: "CIDR for all IP addresses"

Resources:

 # Create an EC2 instance for Docker testing running Amazon Linux 2
  DockerPlaygroundInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - "installDocker"
        installDocker:
          # Commands are executed in alphabetical order
          commands:
            00Begin:
              command: echo "Beginning Install Docker Step (CF::Init)"
            01UpdatePackages:
              command: sudo yum update -y
            02InstallDocker:
              command: sudo amazon-linux-extras install docker
            03StartDocker:
              command: sudo service docker start
            04ChangeDockerUnixGroup:
              command: sudo usermod -a -G docker ec2-user
            05TestDocker:
              command: docker --version
            06GetDockerInfo:
              command: docker system info
            07End:
              command: echo "Finishing Install Docker Step (CF::Init)"
    Properties:
      # us-east-1 Amazon Linux 2
      ImageId: "ami-035be7bafff33b6b6"
      InstanceType: "t2.micro"
      KeyName: "sandbox-docker-playground-key"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref DockerPlaygroundSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            echo "Beginning UserData Step"
            sudo yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v -s ${AWS::StackName} -r DockerPlaygroundInstance -c default --region ${AWS::Region}
            echo "Finishing UserData Step"
      Tags:
        -
          Key: Name
          Value: docker-playground-instance

  # Security group for the Docker playground
  DockerPlaygroundSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "sandbox-docker-security-group"
      GroupDescription: "Security Group for the Docker Playground Instance"
      VpcId: !Ref VpcId
      Tags:
        -
          Key: Name
          Value: sandbox-docker-security-group

  # Docker Playground security group rule allowing my computer to connect to the instance via SSH
  DockerPlaygroundSecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DockerPlaygroundSecurityGroup
      IpProtocol: tcp
      ToPort: 22
      FromPort: 22
      CidrIp: !Ref MyCidr

  # Docker Playground security group rule allowing inbound traffic for ping
  DockerPlaygroundSecurityGroupIngressICMP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DockerPlaygroundSecurityGroup
      IpProtocol: icmp
      ToPort: -1
      FromPort: -1
      CidrIp: !Ref PublicCidr

  # Docker Playground security group rule allowing outbound internet access over HTTP
  DockerPlaygroundSecurityGroupEgressHTTP:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref DockerPlaygroundSecurityGroup
      IpProtocol: tcp
      ToPort: 80
      FromPort: 80
      CidrIp: !Ref PublicCidr

  # Docker Playground security group rule allowing outbound internet access over HTTPS
  DockerPlaygroundSecurityGroupEgressHTTPS:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref DockerPlaygroundSecurityGroup
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443
      CidrIp: !Ref PublicCidr