# CloudFormation template for a Elastic Container Service for Kubernetes (EKS) Cluster.
# Parameters are supplied by Terraform.
# Author: Andrew Jarombek
# Date: 3/4/2019

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Container Service for Kubernetes (EKS) Cluster Setup'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Terraform AWS Data"
        Parameters:
          - VpcId
          - Subnet0
          - Subnet1
    ParameterLabels:
      VpcId:
        default: "VPC to deploy the EKS Cluster in"
      Subnet0:
        default: "The first subnet for the EKS Cluster"
      Subnet1:
        default: "The second subnet for the EKS Cluster"

Resources:

  # IAM role required by an EKS Cluster
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/sandbox/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  # The Kubernetes cluster requires a security group
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubernetes Cluster Security Group for Communication with Worker Nodes
      VpcId: !Ref VpcId

  # EKS cluster for running a Kubernetes control plane across multiple availability zones
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: "sandbox"
      Version: "1.0"
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1

Outputs:

  EKSClusterName:
    Value: !Ref Cluster
    Description: The name of the EKS Cluster
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}ClusterName"

  EKSClusterARN:
    Value: !GetAtt Cluster.Arn
    Description: The Amazon Resource Name of the EKS Cluster
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}ClusterARN"