# CloudFormation template for Elastic Container Service for Kubernetes (EKS).
# Parameters are supplied by Terraform.
# Author: Andrew Jarombek
# Date: 3/4/2019

AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Elastic Container Service for Kubernetes (EKS) Setup
Resources:
  # IAM role required by an EKS Cluster
  EKSRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/sandbox/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: "sandbox"
      Version: "1.0"
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: [""]
        SubnetIds: [""]